NEPTUNE_API_KEY = "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIwZTNlODVlMi0xMzIyLTQwYzQtYmNkYy1kNWYyZmM1MGFiMjcifQ=="
BASE_MODEL_LIST = ["vgg16", "vgg19"]
DATASET_NAME_LIST = ["coco/2017", "voc/2007", "voc/2012"]
GITHUB_UID = "wonhyung64"
GITHUB_TOKEN = "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"
